service: notes-app-ext-database

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-ExtNotes

provider:
  name: aws
  stage: dev
  region: eu-north-1

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

  Outputs:
    NotesTableArn:
      Value:
        Fn::GetAtt:
          - NotesTable
          - Arn
      Export:
        Name: ${self:custom.stage}-ExtNotesTableArn

    NotesTableName:
      Value:
        Ref: NotesTable
      Export:
        Name: ${self:custom.stage}-ExtNotesTable
